# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46ba72aeac1dadd8c308936e46e1449ffb8f6d24dd56f4fc7af1ef9258aedc045ac017b08618f4e1b8d407b807135be792e0faffa4994f5344f86b191c5fb039

test:
  secret_key_base: 4bbd7692bd7c1f35fa9aeb827f9a1bae7ecc8486edf607123bd7d27378207f50a4e9bb99815b5298ca9f32ba32fb41a016806f57e34c12ce3560fce635c50fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
